export const fields = [
  {
    type: "text",
    name: "firstName",
    label: "Name",
    rules: { required: false },
  },
  {
    type: "text",
    name: "lastName",
    label: "Surname",
    rules: { required: false },
  },
  {
    type: "text",
    name: "middleName",
    label: "Middle name",
    rules: { required: false },
  },
  {
    type: "text",
    name: "phone",
    label: "Telephone",
    rules: { required: false },
  },
  {
    type: "text",
    name: "login",
    label: "Login",
    rules: { required: false },
  },
  {
    type: "text",
    name: "password",
    label: "Password",
    rules: { required: false },
  },
  {
    type: "text",
    name: "email",
    label: "Email",
    rules: { required: false },
  },
  {
    type: "text",
    name: "email_password",
    label: "Password от почты",
    rules: { required: false },
  },
  {
    type: "text",
    name: "geo",
    label: "ГЕО",
    rules: { required: false },
  },
  {
    type: "date",
    name: "birthDate",
    label: "Дата рождения",
    rules: { required: false },
    minWidth: "150px",
  },
  {
    type: "text",
    name: "registeredDate",
    label: "Дата регистрации",
    rules: { required: false },
  },
  {
    type: "text",
    name: "account_id",
    label: "ID аккаунта",
    rules: { required: false },
  },
  {
    type: "text",
    name: "friend",
    label: "Друзья",
    rules: { required: false },
  },
  {
    type: "text",
    name: "antidetect_cookie",
    label: "Куки для антидитект",
    rules: { required: false },
  },
  {
    type: "text",
    name: "issue_date",
    label: "Дата выдачи из базы",
    rules: { required: false },
  },
  {
    type: "text",
    name: "eaab_token",
    label: "Токен EAAB",
    rules: { required: false },
  },
  {
    type: "text",
    name: "fan_page",
    label: "Fan Page",
    rules: { required: false },
  },
  {
    type: "text",
    name: "fan_page",
    label: "Fan Page",
    rules: { required: false },
  },
  {
    type: "text",
    name: "user_agent",
    label: "User Agent",
    rules: { required: false },
  },
  {
    type: "text",
    name: "selfie_photo",
    label: "Selfie photo",
    rules: { required: false },
  },
  {
    type: "text",
    name: "pk_id",
    label: "RK ID",
    rules: { required: false },
  },
  {
    type: "text",
    name: "bm_id",
    label: "BM ID",
    rules: { required: false },
  },
  {
    type: "text",
    name: "bm_token",
    label: "BM token",
    rules: { required: false },
  },
  {
    type: "text",
    name: "bm_url",
    label: "BM link",
    rules: { required: false },
  },
  {
    type: "number",
    name: "price",
    label: "Price",
    rules: { required: false },
  },
  {
    type: "select",
    name: "status",
    label: "Status",
    rules: { required: false },
    options: [
      {
        value: "waiting",
        label: "Waiting",
      },
    ],
  },
  {
    type: "text",
    name: "user_id",
    label: "User ID",
    rules: { required: false },
  },
  {
    type: "select",
    name: "type_os",
    label: "User ID",
    rules: { required: false },
    options: [
      {
        label: "Facebook",
        value: "Facebook",
      },
      {
        label: "Tiktok",
        value: "Tiktok",
      },
      {
        label: "Instagram",
        value: "Instagram",
      },
      {
        label: "YouTube",
        value: "YouTube",
      },
    ],
  },
  {
    type: "date",
    name: "date_pay",
    label: "Payment date",
    rules: { required: false },
    minWidth: "150px",
  },
];
