export const tableData = [
  {
    appeal: "",
    loctation: "",
    status: "",
    status_deadline: "",
    status_end: "",
    created_at: "",
    manager: "",
    client: "",
    ad_firm: "",
    comments: "",
  },
  {
    appeal: "",
    loctation: "",
    status: "",
    status_deadline: "",
    status_end: "",
    created_at: "",
    manager: "",
    client: "",
    ad_firm: "",
    comments: "",
  },
  {
    appeal: "",
    loctation: "",
    status: "",
    status_deadline: "",
    status_end: "",
    created_at: "",
    manager: "",
    client: "",
    ad_firm: "",
    comments: "",
  },
  {
    appeal: "",
    loctation: "",
    status: "",
    status_deadline: "",
    status_end: "",
    created_at: "",
    manager: "",
    client: "",
    ad_firm: "",
    comments: "",
  },
  {
    appeal: "",
    loctation: "",
    status: "",
    status_deadline: "",
    status_end: "",
    created_at: "",
    manager: "",
    client: "",
    ad_firm: "",
    comments: "",
  },
  {
    appeal: "",
    loctation: "",
    status: "",
    status_deadline: "",
    status_end: "",
    created_at: "",
    manager: "",
    client: "",
    ad_firm: "",
    comments: "",
  },
  {
    appeal: "",
    loctation: "",
    status: "",
    status_deadline: "",
    status_end: "",
    created_at: "",
    manager: "",
    client: "",
    ad_firm: "",
    comments: "",
  },
  {
    appeal: "",
    loctation: "",
    status: "",
    status_deadline: "",
    status_end: "",
    created_at: "",
    manager: "",
    client: "",
    ad_firm: "",
    comments: "",
  },
  {
    appeal: "",
    loctation: "",
    status: "",
    status_deadline: "",
    status_end: "",
    created_at: "",
    manager: "",
    client: "",
    ad_firm: "",
    comments: "",
  },
];

export const selectGroup = [
  {
    label: "Срок выполнения",
    name: "manager",
    options: [
      {
        value: "1",
        label: "Сергей Антонов",
      },
      {
        value: "2",
        label: "Сергей Антонов",
      },
      {
        value: "3",
        label: "Сергей Антонов",
      },
    ],
  },
  {
    label: "Локация",
    name: "manager",
    options: [
      {
        value: "1",
        label: "Сергей Антонов",
      },
      {
        value: "2",
        label: "Сергей Антонов",
      },
      {
        value: "3",
        label: "Сергей Антонов",
      },
    ],
  },
  {
    label: "Status",
    name: "manager",
    options: [
      {
        value: "1",
        label: "Сергей Антонов",
      },
      {
        value: "2",
        label: "Сергей Антонов",
      },
      {
        value: "3",
        label: "Сергей Антонов",
      },
    ],
  },
  {
    label: "Менеджеры",
    name: "status",
    options: [
      {
        value: "1",
        label: "Активен",
      },
      {
        value: "2",
        label: "Блокирован",
      },
      {
        value: "3",
        label: "Ожидание",
      },
    ],
  },
];
